name: DASH Client Builder
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile DLL
        run: |
          cl.exe /LD main.cpp Client.cpp /Fe:DASH_Client.dll /EHsc /D_USRDLL /D_WINDLL user32.lib gdi32.lib
          
      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: DASH-Final-DLL
          path: DASH_Client.dll
